# Tensor Operation

In [2]:
import numpy as np

<h2>1. Element-wise operation</h2>

In [15]:
x=np.array([[1,2],[2,-4]])
print(len(x.shape))

def naive_relu(x):
    x=x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i,j] = max(x[i,j],0)
    print(x)
naive_relu(x)

print(x)
z=np.maximum(x,0)
print(z)
print(x)

2
[[1 2]
 [2 0]]
[[ 1  2]
 [ 2 -4]]
[[1 2]
 [2 0]]
[[ 1  2]
 [ 2 -4]]


<h2>2. Broadcasting</h2>

In [23]:
x = np.array([[2,3,4],[3,4,5]])
y = np.array([1,2,3])
z = np.add(x,y)
print(x)
print(y)
print(z)

[[2 3 4]
 [3 4 5]]
[1 2 3]
[[3 5 7]
 [4 6 8]]


<h2>3. Tensor Product</h2>

In [22]:
x = np.array([[2,3,4],[3,4,5]])
y = np.array([1,2,3])
z= np.dot(x,y)
print(z)

[20 26]


<h2>4. Tensor Reshaping</h2>

In [26]:
x=np.array([[0,1],[2,3],[4,5]])
print(x.shape)
x = x.reshape((6,1))
print(x)
print(x.shape)

(3, 2)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [28]:
x=np.transpose(x)
print(x)
print(x.shape)

[[0 1 2 3 4 5]]
(1, 6)
